name: 'Import Commit Pragmas'
description: 'Import Commit Pragmas'
inputs:
  commit-message:
    description: 'Commit Message'
    required: true
runs:
  using: "composite"
  steps:
    - name: Show environment
      run: env
      shell: bash
    - run: . ci/gha_functions.sh;
           echo "${{ inputs.commit-message }}" |
             sed -e "s/'/'\"'\"'/g" |
             get_commit_pragmas |
             sed -e 's/^/CP_/' >> $GITHUB_ENV
      shell: bash
